# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 943af74f3504047be08d0b136a098625e1a2567318e0a701da8dd6003cccf792c279aa9b320fd4e0c81c7fff641c205b21e416da92b106a93406019072e015bc

test:
  secret_key_base: 008859a39806794980548e15682b236bfc8d74d14803b4f6d8d48bb788db6fc790c7a758240e063cbf52f7951ab68e05566313e116e4a2080fda58e4224c9f7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
